### ISSUE TITLE
View not getting updated after orientation change

### ISSUE THREAD

**Issue by iAlex97** [NeoTech-Software/Android-Retainable-Tasks#2]
I have a View that displays a "pie" progress for the Task progress.

After I rotate the screen the progress seems "frozen", but the task successfully completes and I am able to Log.d() the progress. Is there anything else that I have to call in order to update my view again?

Also, how can I send parameters to the onPreExecute method?

**Comment by Rolf-Smit** [comment]
Hey Alex,

First of all thanks for your report. Currently version 0.1.0 is a bit unstable, I'm working on 0.2.0 which I will release today which could fix your problem.

Did you call attachListener in the onStart method after the activity rotated?

Could you post some code?

Also, take a look at the demo app! It contains a "progress view (dialog)" task.

**Also, how can I send parameters to the onPreExecute method?**
You should create a custom Task and use the constructor to provide input parameters. But I'm not sure if you mean the Task.onPreExecute method or the Callback.onPreExecute method?

Like this:

``` Java
public MyTask extends Task<Progress, Result> {

    private final Input input;

    public MyTask(String tag, Input value){
        this.input = input;
    }

    //doInBackground

    protected void onPreExecute() {
        //Use the input here
    }
}
```

**Comment by iAlex97** [comment]
Thank you for your fast reply. That's great!

I am talking about Callback.onPreExecute because it has Task<?, ?> task as parameter, but I'm unsure what is the right method to call.

**Comment by Rolf-Smit** [comment]
You need to call a custom method, and thus need to cast the Task input parameter to your custom Task class. I'm still in doubt whether a generic Input parameter would be helpful because not all tasks need it.

Your task:

``` Java
public MyTask extends Task<Progress, Result> {

    private final Input input;

    public MyTask(String tag, Input value){
        this.input = input;
    }

    //doInBackground

    public Input getInput(){
        return input;
    }
}
```

And the Callback.onPreExecute method:

``` Java
@Override
public void onPostExecute(Task<?, ?> task) {
    if(task.getTag().equals("Your task tag")) {
        MyTask myTask = (MyTask ) task;
        Input input = myTask.getInput();
        //Do something with the input.
    }
}
```

**Comment by Rolf-Smit** [comment]
@iAlex97 version 0.2.0 has been released. It contains quite some changes so I highly recommend to read the documentation again. I think version 0.2.0 is easier to use!

**Comment by iAlex97** [comment]
All right! I can test it right now, but thank you very much for clearing things out.
